In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path(".").absolute().parent.parent))

In [4]:
import pandas as pd

df = pd.read_parquet(
    "../../.docker_volumes/downloads/green_taxi_2023-07.parquet", engine="fastparquet"
)

In [5]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2023-07-01 00:08:06,2023-07-01 00:21:24,N,1.0,75.0,170.0,2.0,3.45,17.0,1.0,0.5,4.45,0.0,NaN,1.0,26.70,1.0,1.0,2.75
1,2.0,2023-07-01 00:56:14,2023-07-01 01:03:28,N,1.0,75.0,262.0,2.0,1.49,10.0,1.0,0.5,3.05,0.0,NaN,1.0,18.30,1.0,1.0,2.75
2,2.0,2023-06-30 23:47:32,2023-06-30 23:47:35,N,5.0,42.0,42.0,2.0,0.00,50.0,0.0,0.0,15.30,0.0,NaN,1.0,66.30,1.0,2.0,0.00
3,2.0,2023-07-01 00:30:12,2023-07-01 00:51:20,N,1.0,33.0,75.0,1.0,9.32,38.0,1.0,0.5,0.00,0.0,NaN,1.0,43.25,2.0,1.0,2.75
4,2.0,2023-07-01 00:46:56,2023-07-01 00:49:02,N,1.0,74.0,74.0,1.0,0.97,5.8,1.0,0.5,0.00,0.0,NaN,1.0,8.30,1.0,1.0,0.00

In [9]:
df.shape

(61343, 20)